export const FLAG_MAP: Record<string, string> = {
  'mexico':        '🇲🇽',
  'nam-phi':       '🇿🇦',
  'han-quoc':      '🇰🇷',
  'sec':           '🇨🇿',
  'canada':        '🇨🇦',
  'bosnia':        '🇧🇦',
  'qatar':         '🇶🇦',
  'thuy-si':       '🇨🇭',
  'my':            '🇺🇸',
  'paraguay':      '🇵🇾',
  'uc':            '🇦🇺',
  'tho-nhi-ky':    '🇹🇷',
  'brazil':        '🇧🇷',
  'maroc':         '🇲🇦',
  'haiti':         '🇭🇹',
  'scotland':      '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'duc':           '🇩🇪',
  'curacao':       '🇨🇼',
  'ha-lan':        '🇳🇱',
  'nhat-ban':      '🇯🇵',
  'bo-bien-nga':   '🇨🇮',
  'ecuador':       '🇪🇨',
  'thuy-dien':     '🇸🇪',
  'tunisia':       '🇹🇳',
  'tay-ban-nha':   '🇪🇸',
  'cape-verde':    '🇨🇻',
  'bi':            '🇧🇪',
  'ai-cap':        '🇪🇬',
  'a-rap-xe-ut':   '🇸🇦',
  'uruguay':       '🇺🇾',
  'iran':          '🇮🇷',
  'new-zealand':   '🇳🇿',
  'phap':          '🇫🇷',
  'senegal':       '🇸🇳',
  'iraq':          '🇮🇶',
  'na-uy':         '🇳🇴',
  'argentina':     '🇦🇷',
  'algeria':       '🇩🇿',
  'ao':            '🇦🇹',
  'jordan':        '🇯🇴',
  'bo-dao-nha':    '🇵🇹',
  'congo-dr':      '🇨🇩',
  'anh':           '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'croatia':       '🇭🇷',
  'ghana':         '🇬🇭',
  'panama':        '🇵🇦',
  'uzbekistan':    '🇺🇿',
  'colombia':      '🇨🇴',
};

export function getFlag(slug: string): string {
  return FLAG_MAP[slug] ?? '🏴';
}
