export interface MockMatch {
  match_id: string;
  match_number: number;
  stage: string;
  group?: string;
  home_team: string;
  home_team_vi: string;
  away_team: string;
  away_team_vi: string;
  home_slug: string;
  away_slug: string;
  kickoff_utc: string;
  stadium: string;
  city: string;
  country: string;
}

// ET = UTC-4 trong mùa hè. Kickoff UTC = ET + 4h
// Ví dụ: 3:00 PM ET = 19:00 UTC

export const MOCK_MATCHES: MockMatch[] = [
  // ─── GROUP STAGE ──────────────────────────────────────────────────────────

  // Thursday, June 11
  {
    match_number: 1,
    match_id: "wc26_001",
    stage: "Vòng Bảng - Bảng A",
    group: "A",
    home_team: "Mexico",
    home_team_vi: "Mexico",
    away_team: "South Africa",
    away_team_vi: "Nam Phi",
    home_slug: "mexico",
    away_slug: "nam-phi",
    kickoff_utc: "2026-06-11T19:00:00Z",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    match_number: 2,
    match_id: "wc26_002",
    stage: "Vòng Bảng - Bảng A",
    group: "A",
    home_team: "South Korea",
    home_team_vi: "Hàn Quốc",
    away_team: "Czechia",
    away_team_vi: "Séc",
    home_slug: "han-quoc",
    away_slug: "sec",
    kickoff_utc: "2026-06-12T02:00:00Z",
    stadium: "Estadio Akron",
    city: "Zapopan",
    country: "Mexico",
  },

  // Friday, June 12
  {
    match_number: 3,
    match_id: "wc26_003",
    stage: "Vòng Bảng - Bảng B",
    group: "B",
    home_team: "Canada",
    home_team_vi: "Canada",
    away_team: "Bosnia & Herzegovina",
    away_team_vi: "Bosnia & Herzegovina",
    home_slug: "canada",
    away_slug: "bosnia",
    kickoff_utc: "2026-06-12T19:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
  },
  {
    match_number: 4,
    match_id: "wc26_004",
    stage: "Vòng Bảng - Bảng D",
    group: "D",
    home_team: "USA",
    home_team_vi: "Mỹ",
    away_team: "Paraguay",
    away_team_vi: "Paraguay",
    home_slug: "my",
    away_slug: "paraguay",
    kickoff_utc: "2026-06-13T01:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },

  // Saturday, June 13
  {
    match_number: 5,
    match_id: "wc26_005",
    stage: "Vòng Bảng - Bảng B",
    group: "B",
    home_team: "Qatar",
    home_team_vi: "Qatar",
    away_team: "Switzerland",
    away_team_vi: "Thụy Sĩ",
    home_slug: "qatar",
    away_slug: "thuy-si",
    kickoff_utc: "2026-06-13T19:00:00Z",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    country: "USA",
  },
  {
    match_number: 6,
    match_id: "wc26_006",
    stage: "Vòng Bảng - Bảng C",
    group: "C",
    home_team: "Brazil",
    home_team_vi: "Brazil",
    away_team: "Morocco",
    away_team_vi: "Maroc",
    home_slug: "brazil",
    away_slug: "maroc",
    kickoff_utc: "2026-06-13T22:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 7,
    match_id: "wc26_007",
    stage: "Vòng Bảng - Bảng C",
    group: "C",
    home_team: "Haiti",
    home_team_vi: "Haiti",
    away_team: "Scotland",
    away_team_vi: "Scotland",
    home_slug: "haiti",
    away_slug: "scotland",
    kickoff_utc: "2026-06-14T01:00:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },

  // Sunday, June 14
  {
    match_number: 8,
    match_id: "wc26_008",
    stage: "Vòng Bảng - Bảng D",
    group: "D",
    home_team: "Australia",
    home_team_vi: "Úc",
    away_team: "Türkiye",
    away_team_vi: "Thổ Nhĩ Kỳ",
    home_slug: "uc",
    away_slug: "tho-nhi-ky",
    kickoff_utc: "2026-06-14T04:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },
  {
    match_number: 9,
    match_id: "wc26_009",
    stage: "Vòng Bảng - Bảng E",
    group: "E",
    home_team: "Germany",
    home_team_vi: "Đức",
    away_team: "Curaçao",
    away_team_vi: "Curaçao",
    home_slug: "duc",
    away_slug: "curacao",
    kickoff_utc: "2026-06-14T17:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 10,
    match_id: "wc26_010",
    stage: "Vòng Bảng - Bảng F",
    group: "F",
    home_team: "Netherlands",
    home_team_vi: "Hà Lan",
    away_team: "Japan",
    away_team_vi: "Nhật Bản",
    home_slug: "ha-lan",
    away_slug: "nhat-ban",
    kickoff_utc: "2026-06-14T20:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 11,
    match_id: "wc26_011",
    stage: "Vòng Bảng - Bảng E",
    group: "E",
    home_team: "Ivory Coast",
    home_team_vi: "Bờ Biển Ngà",
    away_team: "Ecuador",
    away_team_vi: "Ecuador",
    home_slug: "bo-bien-nga",
    away_slug: "ecuador",
    kickoff_utc: "2026-06-14T23:00:00Z",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
  },
  {
    match_number: 12,
    match_id: "wc26_012",
    stage: "Vòng Bảng - Bảng F",
    group: "F",
    home_team: "Sweden",
    home_team_vi: "Thụy Điển",
    away_team: "Tunisia",
    away_team_vi: "Tunisia",
    home_slug: "thuy-dien",
    away_slug: "tunisia",
    kickoff_utc: "2026-06-15T02:00:00Z",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    country: "Mexico",
  },

  // Monday, June 15
  {
    match_number: 13,
    match_id: "wc26_013",
    stage: "Vòng Bảng - Bảng H",
    group: "H",
    home_team: "Spain",
    home_team_vi: "Tây Ban Nha",
    away_team: "Cape Verde",
    away_team_vi: "Cape Verde",
    home_slug: "tay-ban-nha",
    away_slug: "cape-verde",
    kickoff_utc: "2026-06-15T16:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 14,
    match_id: "wc26_014",
    stage: "Vòng Bảng - Bảng G",
    group: "G",
    home_team: "Belgium",
    home_team_vi: "Bỉ",
    away_team: "Egypt",
    away_team_vi: "Ai Cập",
    home_slug: "bi",
    away_slug: "ai-cap",
    kickoff_utc: "2026-06-15T19:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    country: "USA",
  },
  {
    match_number: 15,
    match_id: "wc26_015",
    stage: "Vòng Bảng - Bảng H",
    group: "H",
    home_team: "Saudi Arabia",
    home_team_vi: "Ả Rập Xê Út",
    away_team: "Uruguay",
    away_team_vi: "Uruguay",
    home_slug: "a-rap-xe-ut",
    away_slug: "uruguay",
    kickoff_utc: "2026-06-15T22:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },
  {
    match_number: 16,
    match_id: "wc26_016",
    stage: "Vòng Bảng - Bảng G",
    group: "G",
    home_team: "Iran",
    home_team_vi: "Iran",
    away_team: "New Zealand",
    away_team_vi: "New Zealand",
    home_slug: "iran",
    away_slug: "new-zealand",
    kickoff_utc: "2026-06-16T01:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },

  // Tuesday, June 16
  {
    match_number: 17,
    match_id: "wc26_017",
    stage: "Vòng Bảng - Bảng I",
    group: "I",
    home_team: "France",
    home_team_vi: "Pháp",
    away_team: "Senegal",
    away_team_vi: "Senegal",
    home_slug: "phap",
    away_slug: "senegal",
    kickoff_utc: "2026-06-16T19:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 18,
    match_id: "wc26_018",
    stage: "Vòng Bảng - Bảng I",
    group: "I",
    home_team: "Iraq",
    home_team_vi: "Iraq",
    away_team: "Norway",
    away_team_vi: "Na Uy",
    home_slug: "iraq",
    away_slug: "na-uy",
    kickoff_utc: "2026-06-16T22:00:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },
  {
    match_number: 19,
    match_id: "wc26_019",
    stage: "Vòng Bảng - Bảng J",
    group: "J",
    home_team: "Argentina",
    home_team_vi: "Argentina",
    away_team: "Algeria",
    away_team_vi: "Algeria",
    home_slug: "argentina",
    away_slug: "algeria",
    kickoff_utc: "2026-06-17T01:00:00Z",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },

  // Wednesday, June 17
  {
    match_number: 20,
    match_id: "wc26_020",
    stage: "Vòng Bảng - Bảng J",
    group: "J",
    home_team: "Austria",
    home_team_vi: "Áo",
    away_team: "Jordan",
    away_team_vi: "Jordan",
    home_slug: "ao",
    away_slug: "jordan",
    kickoff_utc: "2026-06-17T04:00:00Z",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    country: "USA",
  },
  {
    match_number: 21,
    match_id: "wc26_021",
    stage: "Vòng Bảng - Bảng K",
    group: "K",
    home_team: "Portugal",
    home_team_vi: "Bồ Đào Nha",
    away_team: "DR Congo",
    away_team_vi: "Congo DR",
    home_slug: "bo-dao-nha",
    away_slug: "congo-dr",
    kickoff_utc: "2026-06-17T17:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 22,
    match_id: "wc26_022",
    stage: "Vòng Bảng - Bảng L",
    group: "L",
    home_team: "England",
    home_team_vi: "Anh",
    away_team: "Croatia",
    away_team_vi: "Croatia",
    home_slug: "anh",
    away_slug: "croatia",
    kickoff_utc: "2026-06-17T20:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 23,
    match_id: "wc26_023",
    stage: "Vòng Bảng - Bảng L",
    group: "L",
    home_team: "Ghana",
    home_team_vi: "Ghana",
    away_team: "Panama",
    away_team_vi: "Panama",
    home_slug: "ghana",
    away_slug: "panama",
    kickoff_utc: "2026-06-17T23:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
  },
  {
    match_number: 24,
    match_id: "wc26_024",
    stage: "Vòng Bảng - Bảng K",
    group: "K",
    home_team: "Uzbekistan",
    home_team_vi: "Uzbekistan",
    away_team: "Colombia",
    away_team_vi: "Colombia",
    home_slug: "uzbekistan",
    away_slug: "colombia",
    kickoff_utc: "2026-06-18T02:00:00Z",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
  },

  // Thursday, June 18
  {
    match_number: 25,
    match_id: "wc26_025",
    stage: "Vòng Bảng - Bảng A",
    group: "A",
    home_team: "Czechia",
    home_team_vi: "Séc",
    away_team: "South Africa",
    away_team_vi: "Nam Phi",
    home_slug: "sec",
    away_slug: "nam-phi",
    kickoff_utc: "2026-06-18T16:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 26,
    match_id: "wc26_026",
    stage: "Vòng Bảng - Bảng B",
    group: "B",
    home_team: "Switzerland",
    home_team_vi: "Thụy Sĩ",
    away_team: "Bosnia & Herzegovina",
    away_team_vi: "Bosnia & Herzegovina",
    home_slug: "thuy-si",
    away_slug: "bosnia",
    kickoff_utc: "2026-06-18T19:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },
  {
    match_number: 27,
    match_id: "wc26_027",
    stage: "Vòng Bảng - Bảng B",
    group: "B",
    home_team: "Canada",
    home_team_vi: "Canada",
    away_team: "Qatar",
    away_team_vi: "Qatar",
    home_slug: "canada",
    away_slug: "qatar",
    kickoff_utc: "2026-06-18T22:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },
  {
    match_number: 28,
    match_id: "wc26_028",
    stage: "Vòng Bảng - Bảng A",
    group: "A",
    home_team: "Mexico",
    home_team_vi: "Mexico",
    away_team: "South Korea",
    away_team_vi: "Hàn Quốc",
    home_slug: "mexico",
    away_slug: "han-quoc",
    kickoff_utc: "2026-06-19T01:00:00Z",
    stadium: "Estadio Akron",
    city: "Zapopan",
    country: "Mexico",
  },

  // Friday, June 19
  {
    match_number: 29,
    match_id: "wc26_029",
    stage: "Vòng Bảng - Bảng D",
    group: "D",
    home_team: "USA",
    home_team_vi: "Mỹ",
    away_team: "Australia",
    away_team_vi: "Úc",
    home_slug: "my",
    away_slug: "uc",
    kickoff_utc: "2026-06-19T19:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    country: "USA",
  },
  {
    match_number: 30,
    match_id: "wc26_030",
    stage: "Vòng Bảng - Bảng C",
    group: "C",
    home_team: "Scotland",
    home_team_vi: "Scotland",
    away_team: "Morocco",
    away_team_vi: "Maroc",
    home_slug: "scotland",
    away_slug: "maroc",
    kickoff_utc: "2026-06-19T22:00:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },
  {
    match_number: 31,
    match_id: "wc26_031",
    stage: "Vòng Bảng - Bảng C",
    group: "C",
    home_team: "Brazil",
    home_team_vi: "Brazil",
    away_team: "Haiti",
    away_team_vi: "Haiti",
    home_slug: "brazil",
    away_slug: "haiti",
    kickoff_utc: "2026-06-20T00:30:00Z",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
  },
  {
    match_number: 32,
    match_id: "wc26_032",
    stage: "Vòng Bảng - Bảng D",
    group: "D",
    home_team: "Türkiye",
    home_team_vi: "Thổ Nhĩ Kỳ",
    away_team: "Paraguay",
    away_team_vi: "Paraguay",
    home_slug: "tho-nhi-ky",
    away_slug: "paraguay",
    kickoff_utc: "2026-06-20T03:00:00Z",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    country: "USA",
  },

  // Saturday, June 20
  {
    match_number: 33,
    match_id: "wc26_033",
    stage: "Vòng Bảng - Bảng F",
    group: "F",
    home_team: "Netherlands",
    home_team_vi: "Hà Lan",
    away_team: "Sweden",
    away_team_vi: "Thụy Điển",
    home_slug: "ha-lan",
    away_slug: "thuy-dien",
    kickoff_utc: "2026-06-20T17:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 34,
    match_id: "wc26_034",
    stage: "Vòng Bảng - Bảng E",
    group: "E",
    home_team: "Germany",
    home_team_vi: "Đức",
    away_team: "Ivory Coast",
    away_team_vi: "Bờ Biển Ngà",
    home_slug: "duc",
    away_slug: "bo-bien-nga",
    kickoff_utc: "2026-06-20T20:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
  },
  {
    match_number: 35,
    match_id: "wc26_035",
    stage: "Vòng Bảng - Bảng E",
    group: "E",
    home_team: "Ecuador",
    home_team_vi: "Ecuador",
    away_team: "Curaçao",
    away_team_vi: "Curaçao",
    home_slug: "ecuador",
    away_slug: "curacao",
    kickoff_utc: "2026-06-21T00:00:00Z",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },

  // Sunday, June 21
  {
    match_number: 36,
    match_id: "wc26_036",
    stage: "Vòng Bảng - Bảng F",
    group: "F",
    home_team: "Tunisia",
    home_team_vi: "Tunisia",
    away_team: "Japan",
    away_team_vi: "Nhật Bản",
    home_slug: "tunisia",
    away_slug: "nhat-ban",
    kickoff_utc: "2026-06-21T04:00:00Z",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    country: "Mexico",
  },
  {
    match_number: 37,
    match_id: "wc26_037",
    stage: "Vòng Bảng - Bảng H",
    group: "H",
    home_team: "Spain",
    home_team_vi: "Tây Ban Nha",
    away_team: "Saudi Arabia",
    away_team_vi: "Ả Rập Xê Út",
    home_slug: "tay-ban-nha",
    away_slug: "a-rap-xe-ut",
    kickoff_utc: "2026-06-21T16:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 38,
    match_id: "wc26_038",
    stage: "Vòng Bảng - Bảng G",
    group: "G",
    home_team: "Belgium",
    home_team_vi: "Bỉ",
    away_team: "Iran",
    away_team_vi: "Iran",
    home_slug: "bi",
    away_slug: "iran",
    kickoff_utc: "2026-06-21T19:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },
  {
    match_number: 39,
    match_id: "wc26_039",
    stage: "Vòng Bảng - Bảng H",
    group: "H",
    home_team: "Uruguay",
    home_team_vi: "Uruguay",
    away_team: "Cape Verde",
    away_team_vi: "Cape Verde",
    home_slug: "uruguay",
    away_slug: "cape-verde",
    kickoff_utc: "2026-06-21T22:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },
  {
    match_number: 40,
    match_id: "wc26_040",
    stage: "Vòng Bảng - Bảng G",
    group: "G",
    home_team: "New Zealand",
    home_team_vi: "New Zealand",
    away_team: "Egypt",
    away_team_vi: "Ai Cập",
    home_slug: "new-zealand",
    away_slug: "ai-cap",
    kickoff_utc: "2026-06-22T01:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },

  // Monday, June 22
  {
    match_number: 41,
    match_id: "wc26_041",
    stage: "Vòng Bảng - Bảng J",
    group: "J",
    home_team: "Argentina",
    home_team_vi: "Argentina",
    away_team: "Austria",
    away_team_vi: "Áo",
    home_slug: "argentina",
    away_slug: "ao",
    kickoff_utc: "2026-06-22T17:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 42,
    match_id: "wc26_042",
    stage: "Vòng Bảng - Bảng I",
    group: "I",
    home_team: "France",
    home_team_vi: "Pháp",
    away_team: "Iraq",
    away_team_vi: "Iraq",
    home_slug: "phap",
    away_slug: "iraq",
    kickoff_utc: "2026-06-22T21:00:00Z",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
  },
  {
    match_number: 43,
    match_id: "wc26_043",
    stage: "Vòng Bảng - Bảng I",
    group: "I",
    home_team: "Norway",
    home_team_vi: "Na Uy",
    away_team: "Senegal",
    away_team_vi: "Senegal",
    home_slug: "na-uy",
    away_slug: "senegal",
    kickoff_utc: "2026-06-23T00:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 44,
    match_id: "wc26_044",
    stage: "Vòng Bảng - Bảng J",
    group: "J",
    home_team: "Jordan",
    home_team_vi: "Jordan",
    away_team: "Algeria",
    away_team_vi: "Algeria",
    home_slug: "jordan",
    away_slug: "algeria",
    kickoff_utc: "2026-06-23T03:00:00Z",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    country: "USA",
  },

  // Tuesday, June 23
  {
    match_number: 45,
    match_id: "wc26_045",
    stage: "Vòng Bảng - Bảng K",
    group: "K",
    home_team: "Portugal",
    home_team_vi: "Bồ Đào Nha",
    away_team: "Uzbekistan",
    away_team_vi: "Uzbekistan",
    home_slug: "bo-dao-nha",
    away_slug: "uzbekistan",
    kickoff_utc: "2026-06-23T17:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 46,
    match_id: "wc26_046",
    stage: "Vòng Bảng - Bảng L",
    group: "L",
    home_team: "England",
    home_team_vi: "Anh",
    away_team: "Ghana",
    away_team_vi: "Ghana",
    home_slug: "anh",
    away_slug: "ghana",
    kickoff_utc: "2026-06-23T20:00:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },
  {
    match_number: 47,
    match_id: "wc26_047",
    stage: "Vòng Bảng - Bảng L",
    group: "L",
    home_team: "Panama",
    home_team_vi: "Panama",
    away_team: "Croatia",
    away_team_vi: "Croatia",
    home_slug: "panama",
    away_slug: "croatia",
    kickoff_utc: "2026-06-23T23:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
  },
  {
    match_number: 48,
    match_id: "wc26_048",
    stage: "Vòng Bảng - Bảng K",
    group: "K",
    home_team: "Colombia",
    home_team_vi: "Colombia",
    away_team: "DR Congo",
    away_team_vi: "Congo DR",
    home_slug: "colombia",
    away_slug: "congo-dr",
    kickoff_utc: "2026-06-24T02:00:00Z",
    stadium: "Estadio Akron",
    city: "Zapopan",
    country: "Mexico",
  },

  // Wednesday, June 24 – Final Matchday Groups B & C & A (simultaneous)
  {
    match_number: 49,
    match_id: "wc26_049",
    stage: "Vòng Bảng - Bảng B",
    group: "B",
    home_team: "Switzerland",
    home_team_vi: "Thụy Sĩ",
    away_team: "Canada",
    away_team_vi: "Canada",
    home_slug: "thuy-si",
    away_slug: "canada",
    kickoff_utc: "2026-06-24T19:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },
  {
    match_number: 50,
    match_id: "wc26_050",
    stage: "Vòng Bảng - Bảng B",
    group: "B",
    home_team: "Bosnia & Herzegovina",
    home_team_vi: "Bosnia & Herzegovina",
    away_team: "Qatar",
    away_team_vi: "Qatar",
    home_slug: "bosnia",
    away_slug: "qatar",
    kickoff_utc: "2026-06-24T19:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    country: "USA",
  },
  {
    match_number: 51,
    match_id: "wc26_051",
    stage: "Vòng Bảng - Bảng C",
    group: "C",
    home_team: "Scotland",
    home_team_vi: "Scotland",
    away_team: "Brazil",
    away_team_vi: "Brazil",
    home_slug: "scotland",
    away_slug: "brazil",
    kickoff_utc: "2026-06-24T22:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },
  {
    match_number: 52,
    match_id: "wc26_052",
    stage: "Vòng Bảng - Bảng C",
    group: "C",
    home_team: "Morocco",
    home_team_vi: "Maroc",
    away_team: "Haiti",
    away_team_vi: "Haiti",
    home_slug: "maroc",
    away_slug: "haiti",
    kickoff_utc: "2026-06-24T22:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 53,
    match_id: "wc26_053",
    stage: "Vòng Bảng - Bảng A",
    group: "A",
    home_team: "Czechia",
    home_team_vi: "Séc",
    away_team: "Mexico",
    away_team_vi: "Mexico",
    home_slug: "sec",
    away_slug: "mexico",
    kickoff_utc: "2026-06-25T01:00:00Z",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    match_number: 54,
    match_id: "wc26_054",
    stage: "Vòng Bảng - Bảng A",
    group: "A",
    home_team: "South Africa",
    home_team_vi: "Nam Phi",
    away_team: "South Korea",
    away_team_vi: "Hàn Quốc",
    home_slug: "nam-phi",
    away_slug: "han-quoc",
    kickoff_utc: "2026-06-25T01:00:00Z",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    country: "Mexico",
  },

  // Thursday, June 25 – Final Matchday Groups E, F, D
  {
    match_number: 55,
    match_id: "wc26_055",
    stage: "Vòng Bảng - Bảng E",
    group: "E",
    home_team: "Curaçao",
    home_team_vi: "Curaçao",
    away_team: "Ivory Coast",
    away_team_vi: "Bờ Biển Ngà",
    home_slug: "curacao",
    away_slug: "bo-bien-nga",
    kickoff_utc: "2026-06-25T20:00:00Z",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
  },
  {
    match_number: 56,
    match_id: "wc26_056",
    stage: "Vòng Bảng - Bảng E",
    group: "E",
    home_team: "Ecuador",
    home_team_vi: "Ecuador",
    away_team: "Germany",
    away_team_vi: "Đức",
    home_slug: "ecuador",
    away_slug: "duc",
    kickoff_utc: "2026-06-25T20:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 57,
    match_id: "wc26_057",
    stage: "Vòng Bảng - Bảng F",
    group: "F",
    home_team: "Japan",
    home_team_vi: "Nhật Bản",
    away_team: "Sweden",
    away_team_vi: "Thụy Điển",
    home_slug: "nhat-ban",
    away_slug: "thuy-dien",
    kickoff_utc: "2026-06-25T23:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 58,
    match_id: "wc26_058",
    stage: "Vòng Bảng - Bảng F",
    group: "F",
    home_team: "Tunisia",
    home_team_vi: "Tunisia",
    away_team: "Netherlands",
    away_team_vi: "Hà Lan",
    home_slug: "tunisia",
    away_slug: "ha-lan",
    kickoff_utc: "2026-06-25T23:00:00Z",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },
  {
    match_number: 59,
    match_id: "wc26_059",
    stage: "Vòng Bảng - Bảng D",
    group: "D",
    home_team: "Türkiye",
    home_team_vi: "Thổ Nhĩ Kỳ",
    away_team: "USA",
    away_team_vi: "Mỹ",
    home_slug: "tho-nhi-ky",
    away_slug: "my",
    kickoff_utc: "2026-06-26T02:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },
  {
    match_number: 60,
    match_id: "wc26_060",
    stage: "Vòng Bảng - Bảng D",
    group: "D",
    home_team: "Paraguay",
    home_team_vi: "Paraguay",
    away_team: "Australia",
    away_team_vi: "Úc",
    home_slug: "paraguay",
    away_slug: "uc",
    kickoff_utc: "2026-06-26T02:00:00Z",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    country: "USA",
  },

  // Friday, June 26 – Final Matchday Groups I, H, G
  {
    match_number: 61,
    match_id: "wc26_061",
    stage: "Vòng Bảng - Bảng I",
    group: "I",
    home_team: "Norway",
    home_team_vi: "Na Uy",
    away_team: "France",
    away_team_vi: "Pháp",
    home_slug: "na-uy",
    away_slug: "phap",
    kickoff_utc: "2026-06-26T19:00:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },
  {
    match_number: 62,
    match_id: "wc26_062",
    stage: "Vòng Bảng - Bảng I",
    group: "I",
    home_team: "Senegal",
    home_team_vi: "Senegal",
    away_team: "Iraq",
    away_team_vi: "Iraq",
    home_slug: "senegal",
    away_slug: "iraq",
    kickoff_utc: "2026-06-26T19:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
  },
  {
    match_number: 63,
    match_id: "wc26_063",
    stage: "Vòng Bảng - Bảng H",
    group: "H",
    home_team: "Cape Verde",
    home_team_vi: "Cape Verde",
    away_team: "Saudi Arabia",
    away_team_vi: "Ả Rập Xê Út",
    home_slug: "cape-verde",
    away_slug: "a-rap-xe-ut",
    kickoff_utc: "2026-06-27T00:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 64,
    match_id: "wc26_064",
    stage: "Vòng Bảng - Bảng H",
    group: "H",
    home_team: "Uruguay",
    home_team_vi: "Uruguay",
    away_team: "Spain",
    away_team_vi: "Tây Ban Nha",
    home_slug: "uruguay",
    away_slug: "tay-ban-nha",
    kickoff_utc: "2026-06-27T00:00:00Z",
    stadium: "Estadio Akron",
    city: "Zapopan",
    country: "Mexico",
  },
  {
    match_number: 65,
    match_id: "wc26_065",
    stage: "Vòng Bảng - Bảng G",
    group: "G",
    home_team: "Egypt",
    home_team_vi: "Ai Cập",
    away_team: "Iran",
    away_team_vi: "Iran",
    home_slug: "ai-cap",
    away_slug: "iran",
    kickoff_utc: "2026-06-27T03:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    country: "USA",
  },
  {
    match_number: 66,
    match_id: "wc26_066",
    stage: "Vòng Bảng - Bảng G",
    group: "G",
    home_team: "New Zealand",
    home_team_vi: "New Zealand",
    away_team: "Belgium",
    away_team_vi: "Bỉ",
    home_slug: "new-zealand",
    away_slug: "bi",
    kickoff_utc: "2026-06-27T03:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },

  // Saturday, June 27 – Final Matchday Groups L, K, J
  {
    match_number: 67,
    match_id: "wc26_067",
    stage: "Vòng Bảng - Bảng L",
    group: "L",
    home_team: "Panama",
    home_team_vi: "Panama",
    away_team: "England",
    away_team_vi: "Anh",
    home_slug: "panama",
    away_slug: "anh",
    kickoff_utc: "2026-06-27T21:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 68,
    match_id: "wc26_068",
    stage: "Vòng Bảng - Bảng L",
    group: "L",
    home_team: "Croatia",
    home_team_vi: "Croatia",
    away_team: "Ghana",
    away_team_vi: "Ghana",
    home_slug: "croatia",
    away_slug: "ghana",
    kickoff_utc: "2026-06-27T21:00:00Z",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
  },
  {
    match_number: 69,
    match_id: "wc26_069",
    stage: "Vòng Bảng - Bảng K",
    group: "K",
    home_team: "Colombia",
    home_team_vi: "Colombia",
    away_team: "Portugal",
    away_team_vi: "Bồ Đào Nha",
    home_slug: "colombia",
    away_slug: "bo-dao-nha",
    kickoff_utc: "2026-06-27T23:30:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },
  {
    match_number: 70,
    match_id: "wc26_070",
    stage: "Vòng Bảng - Bảng K",
    group: "K",
    home_team: "DR Congo",
    home_team_vi: "Congo DR",
    away_team: "Uzbekistan",
    away_team_vi: "Uzbekistan",
    home_slug: "congo-dr",
    away_slug: "uzbekistan",
    kickoff_utc: "2026-06-27T23:30:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 71,
    match_id: "wc26_071",
    stage: "Vòng Bảng - Bảng J",
    group: "J",
    home_team: "Algeria",
    home_team_vi: "Algeria",
    away_team: "Austria",
    away_team_vi: "Áo",
    home_slug: "algeria",
    away_slug: "ao",
    kickoff_utc: "2026-06-28T02:00:00Z",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },
  {
    match_number: 72,
    match_id: "wc26_072",
    stage: "Vòng Bảng - Bảng J",
    group: "J",
    home_team: "Jordan",
    home_team_vi: "Jordan",
    away_team: "Argentina",
    away_team_vi: "Argentina",
    home_slug: "jordan",
    away_slug: "argentina",
    kickoff_utc: "2026-06-28T02:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },

  // ─── ROUND OF 32 (Match 73–88) ────────────────────────────────────────────

  {
    match_number: 73,
    match_id: "wc26_073",
    stage: "Vòng 1/16",
    home_team: "Runner-up A",
    home_team_vi: "Á quân Bảng A",
    away_team: "Runner-up B",
    away_team_vi: "Á quân Bảng B",
    home_slug: "a-quan-bang-a",
    away_slug: "a-quan-bang-b",
    kickoff_utc: "2026-06-28T19:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },
  {
    match_number: 74,
    match_id: "wc26_074",
    stage: "Vòng 1/16",
    home_team: "Winner E",
    home_team_vi: "Nhất Bảng E",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-e",
    away_slug: "best-3rd-1",
    kickoff_utc: "2026-06-29T20:30:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },
  {
    match_number: 75,
    match_id: "wc26_075",
    stage: "Vòng 1/16",
    home_team: "Winner F",
    home_team_vi: "Nhất Bảng F",
    away_team: "Runner-up C",
    away_team_vi: "Á quân Bảng C",
    home_slug: "nhat-bang-f",
    away_slug: "a-quan-bang-c",
    kickoff_utc: "2026-06-30T01:00:00Z",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    country: "Mexico",
  },
  {
    match_number: 76,
    match_id: "wc26_076",
    stage: "Vòng 1/16",
    home_team: "Winner C",
    home_team_vi: "Nhất Bảng C",
    away_team: "Runner-up F",
    away_team_vi: "Á quân Bảng F",
    home_slug: "nhat-bang-c",
    away_slug: "a-quan-bang-f",
    kickoff_utc: "2026-06-29T17:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 77,
    match_id: "wc26_077",
    stage: "Vòng 1/16",
    home_team: "Winner I",
    home_team_vi: "Nhất Bảng I",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-i",
    away_slug: "best-3rd-2",
    kickoff_utc: "2026-06-30T21:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 78,
    match_id: "wc26_078",
    stage: "Vòng 1/16",
    home_team: "Runner-up E",
    home_team_vi: "Á quân Bảng E",
    away_team: "Runner-up I",
    away_team_vi: "Á quân Bảng I",
    home_slug: "a-quan-bang-e",
    away_slug: "a-quan-bang-i",
    kickoff_utc: "2026-06-30T17:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 79,
    match_id: "wc26_079",
    stage: "Vòng 1/16",
    home_team: "Winner A",
    home_team_vi: "Nhất Bảng A",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-a",
    away_slug: "best-3rd-3",
    kickoff_utc: "2026-07-01T01:00:00Z",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    match_number: 80,
    match_id: "wc26_080",
    stage: "Vòng 1/16",
    home_team: "Winner L",
    home_team_vi: "Nhất Bảng L",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-l",
    away_slug: "best-3rd-4",
    kickoff_utc: "2026-07-01T16:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 81,
    match_id: "wc26_081",
    stage: "Vòng 1/16",
    home_team: "Winner D",
    home_team_vi: "Nhất Bảng D",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-d",
    away_slug: "best-3rd-5",
    kickoff_utc: "2026-07-02T00:00:00Z",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    country: "USA",
  },
  {
    match_number: 82,
    match_id: "wc26_082",
    stage: "Vòng 1/16",
    home_team: "Winner G",
    home_team_vi: "Nhất Bảng G",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-g",
    away_slug: "best-3rd-6",
    kickoff_utc: "2026-07-01T20:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    country: "USA",
  },
  {
    match_number: 83,
    match_id: "wc26_083",
    stage: "Vòng 1/16",
    home_team: "Runner-up K",
    home_team_vi: "Á quân Bảng K",
    away_team: "Runner-up L",
    away_team_vi: "Á quân Bảng L",
    home_slug: "a-quan-bang-k",
    away_slug: "a-quan-bang-l",
    kickoff_utc: "2026-07-02T23:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
  },
  {
    match_number: 84,
    match_id: "wc26_084",
    stage: "Vòng 1/16",
    home_team: "Winner H",
    home_team_vi: "Nhất Bảng H",
    away_team: "Runner-up J",
    away_team_vi: "Á quân Bảng J",
    home_slug: "nhat-bang-h",
    away_slug: "a-quan-bang-j",
    kickoff_utc: "2026-07-02T19:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },
  {
    match_number: 85,
    match_id: "wc26_085",
    stage: "Vòng 1/16",
    home_team: "Winner B",
    home_team_vi: "Nhất Bảng B",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-b",
    away_slug: "best-3rd-7",
    kickoff_utc: "2026-07-03T03:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },
  {
    match_number: 86,
    match_id: "wc26_086",
    stage: "Vòng 1/16",
    home_team: "Winner J",
    home_team_vi: "Nhất Bảng J",
    away_team: "Runner-up H",
    away_team_vi: "Á quân Bảng H",
    home_slug: "nhat-bang-j",
    away_slug: "a-quan-bang-h",
    kickoff_utc: "2026-07-03T22:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },
  {
    match_number: 87,
    match_id: "wc26_087",
    stage: "Vòng 1/16",
    home_team: "Winner K",
    home_team_vi: "Nhất Bảng K",
    away_team: "Best 3rd",
    away_team_vi: "3rd tốt nhất",
    home_slug: "nhat-bang-k",
    away_slug: "best-3rd-8",
    kickoff_utc: "2026-07-04T01:30:00Z",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },
  {
    match_number: 88,
    match_id: "wc26_088",
    stage: "Vòng 1/16",
    home_team: "Runner-up D",
    home_team_vi: "Á quân Bảng D",
    away_team: "Runner-up G",
    away_team_vi: "Á quân Bảng G",
    home_slug: "a-quan-bang-d",
    away_slug: "a-quan-bang-g",
    kickoff_utc: "2026-07-03T18:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },

  // ─── ROUND OF 16 (Match 89–96) ────────────────────────────────────────────

  {
    match_number: 89,
    match_id: "wc26_089",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 74",
    home_team_vi: "Thắng trận 74",
    away_team: "Thắng trận 77",
    away_team_vi: "Thắng trận 77",
    home_slug: "thang-74",
    away_slug: "thang-77",
    kickoff_utc: "2026-07-04T21:00:00Z",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
  },
  {
    match_number: 90,
    match_id: "wc26_090",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 73",
    home_team_vi: "Thắng trận 73",
    away_team: "Thắng trận 75",
    away_team_vi: "Thắng trận 75",
    home_slug: "thang-73",
    away_slug: "thang-75",
    kickoff_utc: "2026-07-04T17:00:00Z",
    stadium: "NRG Stadium",
    city: "Houston",
    country: "USA",
  },
  {
    match_number: 91,
    match_id: "wc26_091",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 76",
    home_team_vi: "Thắng trận 76",
    away_team: "Thắng trận 78",
    away_team_vi: "Thắng trận 78",
    home_slug: "thang-76",
    away_slug: "thang-78",
    kickoff_utc: "2026-07-05T20:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
  {
    match_number: 92,
    match_id: "wc26_092",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 79",
    home_team_vi: "Thắng trận 79",
    away_team: "Thắng trận 80",
    away_team_vi: "Thắng trận 80",
    home_slug: "thang-79",
    away_slug: "thang-80",
    kickoff_utc: "2026-07-06T00:00:00Z",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    match_number: 93,
    match_id: "wc26_093",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 83",
    home_team_vi: "Thắng trận 83",
    away_team: "Thắng trận 84",
    away_team_vi: "Thắng trận 84",
    home_slug: "thang-83",
    away_slug: "thang-84",
    kickoff_utc: "2026-07-06T19:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 94,
    match_id: "wc26_094",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 81",
    home_team_vi: "Thắng trận 81",
    away_team: "Thắng trận 82",
    away_team_vi: "Thắng trận 82",
    home_slug: "thang-81",
    away_slug: "thang-82",
    kickoff_utc: "2026-07-07T00:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    country: "USA",
  },
  {
    match_number: 95,
    match_id: "wc26_095",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 86",
    home_team_vi: "Thắng trận 86",
    away_team: "Thắng trận 88",
    away_team_vi: "Thắng trận 88",
    home_slug: "thang-86",
    away_slug: "thang-88",
    kickoff_utc: "2026-07-07T16:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },
  {
    match_number: 96,
    match_id: "wc26_096",
    stage: "Vòng 1/8",
    home_team: "Thắng trận 85",
    home_team_vi: "Thắng trận 85",
    away_team: "Thắng trận 87",
    away_team_vi: "Thắng trận 87",
    home_slug: "thang-85",
    away_slug: "thang-87",
    kickoff_utc: "2026-07-07T20:00:00Z",
    stadium: "BC Place",
    city: "Vancouver",
    country: "Canada",
  },

  // ─── QUARTERFINALS (Match 97–100) ─────────────────────────────────────────

  {
    match_number: 97,
    match_id: "wc26_097",
    stage: "Tứ Kết",
    home_team: "Thắng trận 89",
    home_team_vi: "Thắng trận 89",
    away_team: "Thắng trận 90",
    away_team_vi: "Thắng trận 90",
    home_slug: "thang-89",
    away_slug: "thang-90",
    kickoff_utc: "2026-07-09T20:00:00Z",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    country: "USA",
  },
  {
    match_number: 98,
    match_id: "wc26_098",
    stage: "Tứ Kết",
    home_team: "Thắng trận 93",
    home_team_vi: "Thắng trận 93",
    away_team: "Thắng trận 94",
    away_team_vi: "Thắng trận 94",
    home_slug: "thang-93",
    away_slug: "thang-94",
    kickoff_utc: "2026-07-10T19:00:00Z",
    stadium: "SoFi Stadium",
    city: "Inglewood",
    country: "USA",
  },
  {
    match_number: 99,
    match_id: "wc26_099",
    stage: "Tứ Kết",
    home_team: "Thắng trận 91",
    home_team_vi: "Thắng trận 91",
    away_team: "Thắng trận 92",
    away_team_vi: "Thắng trận 92",
    home_slug: "thang-91",
    away_slug: "thang-92",
    kickoff_utc: "2026-07-11T21:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },
  {
    match_number: 100,
    match_id: "wc26_100",
    stage: "Tứ Kết",
    home_team: "Thắng trận 95",
    home_team_vi: "Thắng trận 95",
    away_team: "Thắng trận 96",
    away_team_vi: "Thắng trận 96",
    home_slug: "thang-95",
    away_slug: "thang-96",
    kickoff_utc: "2026-07-12T01:00:00Z",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },

  // ─── SEMIFINALS (Match 101–102) ───────────────────────────────────────────

  {
    match_number: 101,
    match_id: "wc26_101",
    stage: "Bán Kết",
    home_team: "Thắng trận 97",
    home_team_vi: "Thắng trận 97",
    away_team: "Thắng trận 98",
    away_team_vi: "Thắng trận 98",
    home_slug: "thang-97",
    away_slug: "thang-98",
    kickoff_utc: "2026-07-14T19:00:00Z",
    stadium: "AT&T Stadium",
    city: "Arlington",
    country: "USA",
  },
  {
    match_number: 102,
    match_id: "wc26_102",
    stage: "Bán Kết",
    home_team: "Thắng trận 99",
    home_team_vi: "Thắng trận 99",
    away_team: "Thắng trận 100",
    away_team_vi: "Thắng trận 100",
    home_slug: "thang-99",
    away_slug: "thang-100",
    kickoff_utc: "2026-07-15T19:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
  },

  // ─── THIRD-PLACE MATCH (Match 103) ────────────────────────────────────────

  {
    match_number: 103,
    match_id: "wc26_103",
    stage: "Tranh Hạng Ba",
    home_team: "Thua trận 101",
    home_team_vi: "Thua trận 101",
    away_team: "Thua trận 102",
    away_team_vi: "Thua trận 102",
    home_slug: "thua-101",
    away_slug: "thua-102",
    kickoff_utc: "2026-07-18T21:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami Gardens",
    country: "USA",
  },

  // ─── WORLD CUP FINAL (Match 104) ──────────────────────────────────────────

  {
    match_number: 104,
    match_id: "wc26_104",
    stage: "Chung Kết",
    home_team: "Thắng trận 101",
    home_team_vi: "Thắng trận 101",
    away_team: "Thắng trận 102",
    away_team_vi: "Thắng trận 102",
    home_slug: "thang-101",
    away_slug: "thang-102",
    kickoff_utc: "2026-07-19T19:00:00Z",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    country: "USA",
  },
];
